name = "2b2m"
author = "jugglebubbles"
version = "1.4.1"
description = "2b2m.org modded anarchy pack."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fecc6ace547e37169d1e9ef7fd52b43453a75a38f1e1f7da3542c2e65ad6200c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[export]
[export.curseforge]
project-id = 1530503
