name = "2b2m"
author = "jugglebubbles"
version = "1.6.0"
description = "2b2m.org modded anarchy pack."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd9b15676a9bca0aea9d480462c0a7df6e13fcd450cfaa2d84fc8257e3757ecd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[export]
[export.curseforge]
project-id = 1530503
